spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root

  config:
    import: "configserver:http://localhost:8888" 
app:
  message: "Order Service running in DEV environment"

logging:
  level:
    root: INFO
    com.yourorg.order: DEBUG

order:
  max-items-per-order: 5
  enable-payment-validation: true
